### ISSUE TITLE
[BUG] Java IllegalArgumentException: programCounter not found

### ISSUE THREAD

**Issue by graysonsaint** [madiali/mips-emulator#19]
### Tasks

- [X] I have carefully followed the instructions in the [README](https://github.com/madiali/mips-emulator).
- [X] I have read through the page [Known bugs and limitations](https://github.com/madiali/mips-emulator/wiki/Known-bugs-and-limitations), and my bug is not described there.
- [X] I have searched for my issue on the [Issues](https://github.com/madiali/mips-emulator/issues) page and did not find it there.
- [X] The issue I am raising is a potential bug and not just a usage question. For a usage question, please go back in your browser and select the Question option.

### Description

I am getting an error whenever I try to run the MIPS emulator:
java.lang.IllegalArgumentException: Required integer field programCounter not found or illegally formatted

I am using the default CatsAndDogs.json and all my mem files are properly named and in the path.

### Reproduction steps

Create folder CatsAndDogs and put all .mem files and CatsAndDogs.json and then run java -jar mips-em...

### Expected behavior

I expect the emulator to run considering the programCounter variable should be initialized to 0 in the JSON file.

**Comment by jesse-wei** [comment]
Can you send a screenshot or paste the JSON you're using @graysonsaint? The error message is pretty explicit here.

Your JSON should have exactly the line

```json
  "programCounter": 0,
```

I have not modified [CatsAndDogs.json](https://github.com/madiali/mips-emulator/blob/main/src/test/ExampleProjects/CatsAndDogs/CatsAndDogs.json) from the version shown to work in the demo video.

**Comment by jesse-wei** [comment]
It's also possible that something else is causing this issue and the error message is not as specific as it should be. I'm going to close this issue for now but can look at your JSON once you post it.

**Comment by jesse-wei** [comment]
It's also possible that something else is causing this issue and the error message is not as specific as it should be. I'm going to close this issue for now but can look at your JSON once you post it.
