### ISSUE TITLE
Index out of bounds error[BUG] 

### ISSUE THREAD

**Issue by emmagoodrich** [madiali/mips-emulator#20]
### Tasks

- [X] I have carefully followed the instructions in the [README](https://github.com/madiali/mips-emulator).
- [X] I have read through the page [Known bugs and limitations](https://github.com/madiali/mips-emulator/wiki/Known-bugs-and-limitations), and my bug is not described there.
- [X] I have searched for my issue on the [Issues](https://github.com/madiali/mips-emulator/issues) page and did not find it there.
- [X] The issue I am raising is a potential bug and not just a usage question. For a usage question, please go back in your browser and select the Question option.

### Description

Asked to report by Montek -  getting Index Out of Bounds error when trying to load .json file
![image](https://github.com/madiali/mips-emulator/assets/77809980/bd17cfa5-44e7-4f26-b27b-f58e37bcb4ac)

### Reproduction steps

1. Go to terminal
2. run 'mips-em'
(not sure if you want my .mem files)

### Expected behavior

Emulator to start running. I did not change anything in the .json file, and all my .mem file names match what is in the file.

### OS

macOS

**Comment by jesse-wei** [comment]
Please paste your JSON file here, I'll check it out

**Comment by jesse-wei** [comment]
Are you using 32x32 (i.e., not 16x16) sprites? Sprites that aren't 16x16 aren't supported.

The exception that occurs is in `VGADisplayBMPController`, which controls the screen, and the error you're getting is related to the screen.

Specifically, I'm seeing "index 300 out of bounds for size 300", and 300 px is the height of the VGA display. Your code should only be attempting to access index 299 at most but is attempting to access 300, for some reason.

Since execution didn't get past the initialize method, it might be your smem file. How many lines are in each of your mem files?

**Comment by jesse-wei** [comment]
Emma is using 32x32 sprites, which is not supported.
