### ISSUE TITLE
Emulator Freezes when dealing with too many function calls. 

### ISSUE THREAD

**Issue by xlhuang37** [madiali/mips-emulator#21]
### Tasks

- [X] I have carefully followed the instructions in the [README](https://github.com/madiali/mips-emulator).
- [X] I have read through the page [Known bugs and limitations](https://github.com/madiali/mips-emulator/wiki/Known-bugs-and-limitations), and my bug is not described there.
- [X] I have searched for my issue on the [Issues](https://github.com/madiali/mips-emulator/issues) page and did not find it there.
- [X] The issue I am raising is a potential bug and not just a usage question. For a usage question, please go back in your browser and select the Question option.

### Description

In my program, one key board action will introduce 2400 functions calls (specifically, getChar and putChar). When this key is pressed, the emulator freezes. When the same instruction mem is imported to the board, the program functions correctly. 
The register t0 and t1 are respectively fixed to 0x10001230 and 0x00001230 after the freeze, which is impossible if the emulator follows my program strictly. 

### Reproduction steps

At a starter, maybe try if this is a performance issue? Do a lot of function calls. 
If that does not reproduce the issue, I can provide my imem file. 

### Expected behavior

Doing 2400 short function calls should not freeze the program. 

### OS

Windows

**Comment by jesse-wei** [comment]
This is an interesting issue. To confirm, I assume every other key works as expected in the emulator and on the board? And just this one key results in different behavior on the emulator and on the board.

When you pause the emulator using the pause button, it will show you the execution speed, as shown below:

<img width="645" alt="image" src="https://github.com/madiali/mips-emulator/assets/69875698/685d4fb8-0599-4428-a413-34cd600a8c46">

Can you let me know what this number is for your program when running normally? Specifically, run normally without pressing that one button and get that number.

In [ExecuteAllThrottled.java](https://github.com/madiali/mips-emulator/blob/main/src/main/java/com/comp541/GUI/ExecuteAllThrottled.java), we use a hardcoded number to throttle execution speed. The example projects usually run at 15-20 MHz, which is the expected range, per project specifications.

```java
private static final double TARGET_CONSTANT = 0.85;
```

(this code is really bad, but it normally works fine)

Maybe you can clone this repo, change this number, and run `Main.java` and see if this affects the behavior of that one button? That'll help me know if it's a performance issue (i.e., we should allow users to adjust `TARGET_CONSTANT` via the JSON) or something else.

Or, ask Prof. Singh if you can send me your four .mem files, and then I can investigate myself.

**Comment by xlhuang37** [comment]
Ok, I found the problem. I used double click to run the java program so I did not have this terminal screen to see the bug message. This was the UnmappedAddressException that is discussed in the known bugs section.
